version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "server"
      POSTGRES_PASSWORD: "server"
    ports:
      - "5432:5432"
